### ISSUE TITLE
Large HackGT logo showing up on home screen sometimes

### ISSUE THREAD

**Issue by kexin-zhang** [HackGT/hackgt-org-website#62]
![screenshot 6](https://user-images.githubusercontent.com/17093911/36462241-312b005e-1690-11e8-9e50-bd0a56dabb9d.png)

**Comment by petschekr** [comment]
This definitely still an issue on random loads (clearing cache, local storage, cookies seems to make it appear more often) and on first load in new browsers.

I've traced this to a bug (race condition) in the way the <svg> element is inserted into the page. It seems like [the HackGT logo](https://github.com/HackGT/hackgt-org-website/blob/54281183328d3dad3444ad42b5ef98790ec198b7/assets/hackgt.svg) is being inserted twice. In the first instance, the #hackgt group is pulled out and moved somewhere else but this doesn't happen for the second logo so it appears in the top left corner.

![screenshot 2](https://user-images.githubusercontent.com/1111373/40758292-a07989e0-645a-11e8-9e68-dca7c201dbc1.png)

**Comment by petschekr** [comment]
Found the source (I think): https://github.com/HackGT/hackgt-org-website/blob/ce98688a84722d2196eda33bc493ab16a63bbd3b/js/home.js#L189

SVG file will be loaded if it doesn't exist on page load in the init() function. Then, after 100 ms timeout, resize() is called automatically calling init() again. If the SVG file hasn't loaded in 100 ms (happens if the cache is cleared and you have a slow network), it will be downloaded twice (or more).
